//Write a method that returns the sum of all even Fibonacci numbers. Consider all Fibonacci numbers that are less than or equal to n.Each new element in the Fibonacci sequence is generated by adding the previous two elements.1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ….
package W1Assignment;
import java.util.Scanner;
public class Fibonacci {
static int n;
public static int fibo(int n)
{
int f1=0,f2=1,sum = 0,evenSum=0;
for (int i=1 ;i<=n;i++)
{
sum = f1 + f2;
f1 = f2;
f2 = sum;
if(sum%2==0)
{
evenSum = evenSum+sum;
}
}
System.out.println("The sum of Even Numbers in fibonacci is "+evenSum);
return evenSum;
}
public static void main (String[]args)
{
Scanner sc = new Scanner(System.in);
int n = sc.nextInt();
Fibonacci.fibo(n);
  
}
 
}